export const MISSING_PORTAL_CONFIG = [
  "AUTH_SECRET",
  "AUTH_DISCORD_ID",
  "AUTH_DISCORD_SECRET",
  "DISCORD_GUILD_ID",
  "EYEDBOT_API_URL",
  "COMMUNITY_API_KEY",
  "COMMUNITY_SIGNING_SECRET",
].filter((name) => !process.env[name]?.trim());

export const IS_PORTAL_CONFIGURED = MISSING_PORTAL_CONFIG.length === 0;
